import fs from 'fs';
import path from 'path';

/**
 * Export contract addresses and ABIs for backend integration
 * Generates TypeScript and JSON files for easy import
 */

interface ContractExport {
  address: string;
  abi: any[];
}

interface ContractsExport {
  network: string;
  chainId: number;
  contracts: {
    VoterRegistry: ContractExport;
    VoteLedger: ContractExport;
    ElectionManager: ContractExport;
  };
  rpcUrl: string;
}

async function main() {
  console.log('='.repeat(60));
  console.log('Exporting Contract Addresses and ABIs for Backend');
  console.log('='.repeat(60));
  console.log();

  // Determine network (default to localhost)
  const chainId = process.env.CHAIN_ID || '1337';
  const networkName = process.env.NETWORK || 'localhost';
  
  console.log('Network:', networkName);
  console.log('Chain ID:', chainId);
  console.log();

  // Load deployment info
  const deploymentsDir = path.join(__dirname, '..', 'deployments');
  const deploymentFile = path.join(deploymentsDir, `deployment-${chainId}.json`);
  
  if (!fs.existsSync(deploymentFile)) {
    throw new Error(
      `Deployment file not found: ${deploymentFile}\n` +
      'Please run: npx hardhat run scripts/deploy-all.ts --network localhost'
    );
  }
  
  const deploymentInfo = JSON.parse(fs.readFileSync(deploymentFile, 'utf8'));
  console.log('Loaded deployment from:', deploymentFile);
  console.log();

  // Load ABIs
  const abisDir = path.join(deploymentsDir, 'abis');
  
  const voterRegistryAbi = JSON.parse(
    fs.readFileSync(path.join(abisDir, 'VoterRegistry.json'), 'utf8')
  );
  
  const voteLedgerAbi = JSON.parse(
    fs.readFileSync(path.join(abisDir, 'VoteLedger.json'), 'utf8')
  );
  
  const electionManagerAbi = JSON.parse(
    fs.readFileSync(path.join(abisDir, 'ElectionManager.json'), 'utf8')
  );

  console.log('Loaded ABIs:');
  console.log('  VoterRegistry:', voterRegistryAbi.length, 'functions/events');
  console.log('  VoteLedger:', voteLedgerAbi.length, 'functions/events');
  console.log('  ElectionManager:', electionManagerAbi.length, 'functions/events');
  console.log();

  // Create export object
  const contractsExport: ContractsExport = {
    network: networkName,
    chainId: parseInt(chainId),
    contracts: {
      VoterRegistry: {
        address: deploymentInfo.contracts.voterRegistry,
        abi: voterRegistryAbi,
      },
      VoteLedger: {
        address: deploymentInfo.contracts.voteLedger,
        abi: voteLedgerAbi,
      },
      ElectionManager: {
        address: deploymentInfo.contracts.electionManager,
        abi: electionManagerAbi,
      },
    },
    rpcUrl: networkName === 'localhost' ? 'http://127.0.0.1:8545' : process.env.RPC_URL || '',
  };

  // Export as JSON
  const exportDir = path.join(__dirname, '..', 'exports');
  if (!fs.existsSync(exportDir)) {
    fs.mkdirSync(exportDir, { recursive: true });
  }
  
  const jsonExportFile = path.join(exportDir, 'contracts.json');
  fs.writeFileSync(jsonExportFile, JSON.stringify(contractsExport, null, 2));
  console.log('✓ Exported JSON:', jsonExportFile);

  // Export as TypeScript module
  const tsExportContent = `/**
 * Auto-generated contract addresses and ABIs
 * Generated at: ${new Date().toISOString()}
 * Network: ${networkName} (Chain ID: ${chainId})
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Regenerate by running: npm run export:contracts
 */

export const NETWORK = '${networkName}';
export const CHAIN_ID = ${chainId};
export const RPC_URL = '${contractsExport.rpcUrl}';

export const VOTER_REGISTRY_ADDRESS = '${deploymentInfo.contracts.voterRegistry}';
export const VOTE_LEDGER_ADDRESS = '${deploymentInfo.contracts.voteLedger}';
export const ELECTION_MANAGER_ADDRESS = '${deploymentInfo.contracts.electionManager}';

export const VOTER_REGISTRY_ABI = ${JSON.stringify(voterRegistryAbi, null, 2)} as const;

export const VOTE_LEDGER_ABI = ${JSON.stringify(voteLedgerAbi, null, 2)} as const;

export const ELECTION_MANAGER_ABI = ${JSON.stringify(electionManagerAbi, null, 2)} as const;

export const CONTRACTS = {
  VoterRegistry: {
    address: VOTER_REGISTRY_ADDRESS,
    abi: VOTER_REGISTRY_ABI,
  },
  VoteLedger: {
    address: VOTE_LEDGER_ADDRESS,
    abi: VOTE_LEDGER_ABI,
  },
  ElectionManager: {
    address: ELECTION_MANAGER_ADDRESS,
    abi: ELECTION_MANAGER_ABI,
  },
} as const;

export default CONTRACTS;
`;

  const tsExportFile = path.join(exportDir, 'contracts.ts');
  fs.writeFileSync(tsExportFile, tsExportContent);
  console.log('✓ Exported TypeScript:', tsExportFile);
  console.log();

  // Create a simplified version for backend (without full ABIs in code)
  const backendExportContent = `/**
 * Contract addresses for backend integration
 * Generated at: ${new Date().toISOString()}
 * Network: ${networkName} (Chain ID: ${chainId})
 */

export const CONTRACT_ADDRESSES = {
  VOTER_REGISTRY: '${deploymentInfo.contracts.voterRegistry}',
  VOTE_LEDGER: '${deploymentInfo.contracts.voteLedger}',
  ELECTION_MANAGER: '${deploymentInfo.contracts.electionManager}',
} as const;

export const BLOCKCHAIN_CONFIG = {
  NETWORK: '${networkName}',
  CHAIN_ID: ${chainId},
  RPC_URL: '${contractsExport.rpcUrl}',
} as const;

// Load ABIs from JSON files
import voterRegistryAbi from './abis/VoterRegistry.json';
import voteLedgerAbi from './abis/VoteLedger.json';
import electionManagerAbi from './abis/ElectionManager.json';

export const CONTRACT_ABIS = {
  VOTER_REGISTRY: voterRegistryAbi,
  VOTE_LEDGER: voteLedgerAbi,
  ELECTION_MANAGER: electionManagerAbi,
} as const;
`;

  const backendExportFile = path.join(exportDir, 'contracts-backend.ts');
  fs.writeFileSync(backendExportFile, backendExportContent);
  console.log('✓ Exported backend config:', backendExportFile);

  // Copy ABIs to export directory
  const exportAbisDir = path.join(exportDir, 'abis');
  if (!fs.existsSync(exportAbisDir)) {
    fs.mkdirSync(exportAbisDir, { recursive: true });
  }
  
  fs.copyFileSync(
    path.join(abisDir, 'VoterRegistry.json'),
    path.join(exportAbisDir, 'VoterRegistry.json')
  );
  fs.copyFileSync(
    path.join(abisDir, 'VoteLedger.json'),
    path.join(exportAbisDir, 'VoteLedger.json')
  );
  fs.copyFileSync(
    path.join(abisDir, 'ElectionManager.json'),
    path.join(exportAbisDir, 'ElectionManager.json')
  );
  
  console.log('✓ Copied ABIs to export directory');
  console.log();

  // ========================================
  // SUMMARY
  // ========================================
  console.log('='.repeat(60));
  console.log('EXPORT SUMMARY');
  console.log('='.repeat(60));
  console.log();
  console.log('Contract Addresses:');
  console.log('  VoterRegistry:', deploymentInfo.contracts.voterRegistry);
  console.log('  VoteLedger:', deploymentInfo.contracts.voteLedger);
  console.log('  ElectionManager:', deploymentInfo.contracts.electionManager);
  console.log();
  console.log('Exported Files:');
  console.log('  JSON:', jsonExportFile);
  console.log('  TypeScript:', tsExportFile);
  console.log('  Backend Config:', backendExportFile);
  console.log('  ABIs Directory:', exportAbisDir);
  console.log();
  console.log('Usage in Backend:');
  console.log('  import { CONTRACT_ADDRESSES, CONTRACT_ABIS } from "./exports/contracts-backend";');
  console.log('  import { Web3 } from "web3";');
  console.log('  const web3 = new Web3("http://127.0.0.1:8545");');
  console.log('  const voterRegistry = new web3.eth.Contract(');
  console.log('    CONTRACT_ABIS.VOTER_REGISTRY,');
  console.log('    CONTRACT_ADDRESSES.VOTER_REGISTRY');
  console.log('  );');
  console.log();
  console.log('✓ Export completed successfully!');
  console.log('='.repeat(60));
}

// Execute export
main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error('Export failed:', error);
    process.exit(1);
  });
